// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghcebusrogjiwhsgrkyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdoY2VidXNyb2dqaXdoc2dya3lnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NzIzNDYsImV4cCI6MjA3MjE0ODM0Nn0.A6UUCRCgMklm0-ULn0RG85iwoTnbsgmQb4tD7_pdKi8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});